/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 09/06/2019 21:45:57
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_SYSCLKFreq_VALUE                     8000000
#define MX_HCLKFreq_Value                       8000000
#define MX_FCLKCortexFreq_Value                 8000000
#define MX_CortexFreq_Value                     8000000
#define MX_AHBFreq_Value                        8000000
#define MX_APB1Freq_Value                       8000000
#define MX_APB2Freq_Value                       8000000
#define MX_APB1TimFreq_Value                    8000000
#define MX_APB2TimFreq_Value                    8000000
#define MX_PWRFreq_Value                        8000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        32000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    8000000

/*-------------------------------- SPI2       --------------------------------*/

#define MX_SPI2                                 1

/* GPIO Configuration */

/* Pin PB13 */
#define MX_SPI2_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_SCK_Pin                         PB13
#define MX_SPI2_SCK_GPIOx                       GPIOB
#define MX_SPI2_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SSD_SCK                              SPI2_SCK
#define MX_SPI2_SCK_GPIO_Pin                    GPIO_PIN_13
#define MX_SPI2_SCK_GPIO_AF                     GPIO_AF5_SPI2
#define MX_SPI2_SCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PB14 */
#define MX_SPI2_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MISO_Pin                        PB14
#define MX_SPI2_MISO_GPIOx                      GPIOB
#define MX_SPI2_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SSD_MISO                             SPI2_MISO
#define MX_SPI2_MISO_GPIO_Pin                   GPIO_PIN_14
#define MX_SPI2_MISO_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MISO_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PB15 */
#define MX_SPI2_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SPI2_MOSI_Pin                        PB15
#define MX_SPI2_MOSI_GPIOx                      GPIOB
#define MX_SPI2_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SSD_MOSI                             SPI2_MOSI
#define MX_SPI2_MOSI_GPIO_Pin                   GPIO_PIN_15
#define MX_SPI2_MOSI_GPIO_AF                    GPIO_AF5_SPI2
#define MX_SPI2_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_PA1_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA1_Pin                              PA1
#define MX_PA1_GPIOx                            GPIOA
#define MX_PA1_PinState                         GPIO_PIN_RESET
#define MX_PA1_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_WR                               PA1
#define MX_PA1_GPIO_Pin                         GPIO_PIN_1
#define MX_PA1_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB2 */
#define MX_PB2_Pin                              PB2
#define MX_PB2_GPIOx                            GPIOB
#define MX_PB2_GPIO_PuPd                        GPIO_NOPULL
#define MX_KEY_RIGHT                            PB2
#define MX_PB2_GPIO_Pin                         GPIO_PIN_2
#define MX_PB2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA4 */
#define MX_PA4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA4_Pin                              PA4
#define MX_PA4_GPIOx                            GPIOA
#define MX_PA4_PinState                         GPIO_PIN_RESET
#define MX_PA4_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_RS                               PA4
#define MX_PA4_GPIO_Pin                         GPIO_PIN_4
#define MX_PA4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB5 */
#define MX_PB5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_PinState                         GPIO_PIN_RESET
#define MX_PB5_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_D4                               PB5
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA6 */
#define MX_PA6_Pin                              PA6
#define MX_PA6_GPIOx                            GPIOA
#define MX_PA6_GPIO_PuPd                        GPIO_NOPULL
#define MX_KEY_LEFT                             PA6
#define MX_PA6_GPIO_Pin                         GPIO_PIN_6
#define MX_PA6_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_D5                               PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC7 */
#define MX_PC7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC7_Pin                              PC7
#define MX_PC7_GPIOx                            GPIOC
#define MX_PC7_PinState                         GPIO_PIN_RESET
#define MX_PC7_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_D1                               PC7
#define MX_PC7_GPIO_Pin                         GPIO_PIN_7
#define MX_PC7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB6 */
#define MX_PB6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB6_GPIO_FM6                         __NULL
#define MX_PB6_Pin                              PB6
#define MX_PB6_GPIOx                            GPIOB
#define MX_PB6_PinState                         GPIO_PIN_RESET
#define MX_PB6_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_D2                               PB6
#define MX_PB6_GPIO_Pin                         GPIO_PIN_6
#define MX_PB6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA8 */
#define MX_PA8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA8_Pin                              PA8
#define MX_PA8_GPIOx                            GPIOA
#define MX_PA8_PinState                         GPIO_PIN_RESET
#define MX_PA8_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_D7                               PA8
#define MX_PA8_GPIO_Pin                         GPIO_PIN_8
#define MX_PA8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA7 */
#define MX_PA7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA7_Pin                              PA7
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_PinState                         GPIO_PIN_RESET
#define MX_PA7_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_D3                               PA7
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7
#define MX_PA7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA9 */
#define MX_PA9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA9_Pin                              PA9
#define MX_PA9_GPIOx                            GPIOA
#define MX_PA9_PinState                         GPIO_PIN_RESET
#define MX_PA9_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_D0                               PA9
#define MX_PA9_GPIO_Pin                         GPIO_PIN_9
#define MX_PA9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB10 */
#define MX_PB10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB10_Pin                             PB10
#define MX_PB10_GPIOx                           GPIOB
#define MX_PB10_PinState                        GPIO_PIN_RESET
#define MX_PB10_GPIO_PuPd                       GPIO_NOPULL
#define MX_LCD_D6                               PB10
#define MX_PB10_GPIO_Pin                        GPIO_PIN_10
#define MX_PB10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA11 */
#define MX_PA11_Pin                             PA11
#define MX_PA11_GPIOx                           GPIOA
#define MX_PA11_GPIO_PuPd                       GPIO_NOPULL
#define MX_KEY_UP                               PA11
#define MX_PA11_GPIO_Pin                        GPIO_PIN_11
#define MX_PA11_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PB12 */
#define MX_PB12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB12_Pin                             PB12
#define MX_PB12_GPIOx                           GPIOB
#define MX_PB12_PinState                        GPIO_PIN_RESET
#define MX_PB12_GPIO_PuPd                       GPIO_NOPULL
#define MX_SSD_CS2                              PB12
#define MX_PB12_GPIO_Pin                        GPIO_PIN_12
#define MX_PB12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB11 */
#define MX_PB11_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB11_Pin                             PB11
#define MX_PB11_GPIOx                           GPIOB
#define MX_PB11_PinState                        GPIO_PIN_RESET
#define MX_PB11_GPIO_PuPd                       GPIO_NOPULL
#define MX_SSD_CS1                              PB11
#define MX_PB11_GPIO_Pin                        GPIO_PIN_11
#define MX_PB11_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA12 */
#define MX_PA12_Pin                             PA12
#define MX_PA12_GPIOx                           GPIOA
#define MX_PA12_GPIO_PuPd                       GPIO_NOPULL
#define MX_KEY_CENTER                           PA12
#define MX_PA12_GPIO_Pin                        GPIO_PIN_12
#define MX_PA12_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PA0 */
#define MX_PA0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA0_Pin                              PA0
#define MX_PA0_GPIOx                            GPIOA
#define MX_PA0_PinState                         GPIO_PIN_RESET
#define MX_PA0_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_RD                               PA0
#define MX_PA0_GPIO_Pin                         GPIO_PIN_0
#define MX_PA0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB1 */
#define MX_PB1_Pin                              PB1
#define MX_PB1_GPIOx                            GPIOB
#define MX_PB1_GPIO_PuPd                        GPIO_NOPULL
#define MX_KEY_DOWN                             PB1
#define MX_PB1_GPIO_Pin                         GPIO_PIN_1
#define MX_PB1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB0 */
#define MX_PB0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB0_Pin                              PB0
#define MX_PB0_GPIOx                            GPIOB
#define MX_PB0_PinState                         GPIO_PIN_RESET
#define MX_PB0_GPIO_PuPd                        GPIO_NOPULL
#define MX_LCD_CS                               PB0
#define MX_PB0_GPIO_Pin                         GPIO_PIN_0
#define MX_PB0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

